// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import * as core from "@linkedctl/core";
import * as callbackServerModule from "./callback-server.js";
import { loginCommand } from "./login.js";
import { Command } from "commander";
import type { CallbackResult } from "./callback-server.js";

vi.mock("@linkedctl/core", async (importOriginal) => {
  const actual = await importOriginal<typeof core>();
  return { ...actual };
});

vi.mock("./callback-server.js", async (importOriginal) => {
  const actual = await importOriginal<typeof callbackServerModule>();
  return { ...actual };
});

vi.mock("node:child_process", () => ({
  execFile: vi.fn(),
}));

/** Create a parent program with the --profile option, as login traverses parent. */
function wrapInProgram(cmd: Command): Command {
  const auth = new Command("auth");
  auth.addCommand(cmd);
  const program = new Command("linkedctl");
  program.option("--profile <name>", "profile to use from config file");
  program.addCommand(auth);
  return program;
}

/**
 * Set up mocks for the full OAuth2 flow. Uses a deferred callback pattern
 * so the callback resolves with the correct state generated by randomUUID.
 */
function mockFullOAuthFlow(overrides?: { exchangeResult?: Partial<core.OAuth2TokenResponse> }) {
  const stopFn = vi.fn<() => Promise<void>>().mockResolvedValue(undefined);

  let resolveCallback!: (value: CallbackResult) => void;
  const callbackResult = new Promise<CallbackResult>((resolve) => {
    resolveCallback = resolve;
  });

  vi.spyOn(callbackServerModule, "startCallbackServer").mockResolvedValue({
    port: 12345,
    result: callbackResult,
    stop: stopFn,
  });

  // When buildAuthorizationUrl is called, resolve the callback with the correct state
  vi.spyOn(core, "buildAuthorizationUrl").mockImplementation((_config, state) => {
    resolveCallback({ code: "auth-code-123", state });
    return "https://fake-auth-url";
  });

  const exchangeSpy = vi.spyOn(core, "exchangeAuthorizationCode").mockResolvedValue({
    accessToken: "new-access-token",
    expiresIn: 5184000,
    refreshToken: "new-refresh-token",
    scope: "openid profile w_member_social",
    ...overrides?.exchangeResult,
  });

  return { stopFn, exchangeSpy };
}

describe("auth login", () => {
  let loadConfigFileSpy: ReturnType<typeof vi.spyOn>;
  let saveOAuthTokensSpy: ReturnType<typeof vi.spyOn>;
  let saveOAuthClientCredentialsSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    loadConfigFileSpy = vi.spyOn(core, "loadConfigFile").mockResolvedValue({ raw: undefined, path: undefined });
    saveOAuthTokensSpy = vi.spyOn(core, "saveOAuthTokens").mockResolvedValue(undefined);
    saveOAuthClientCredentialsSpy = vi.spyOn(core, "saveOAuthClientCredentials").mockResolvedValue(undefined);
    vi.spyOn(console, "log").mockImplementation(() => {});
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("throws when no client credentials provided", async () => {
    const program = wrapInProgram(loginCommand());

    await expect(program.parseAsync(["auth", "login"], { from: "user" })).rejects.toThrow(/Missing OAuth2 credentials/);
  });

  it("performs full OAuth flow with client credentials from flags", async () => {
    const { stopFn } = mockFullOAuthFlow();

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "my-client-id", "--client-secret", "my-client-secret"], {
      from: "user",
    });

    // Verify tokens were saved
    expect(saveOAuthTokensSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        accessToken: "new-access-token",
        refreshToken: "new-refresh-token",
      }),
      { profile: undefined },
    );
    expect(saveOAuthClientCredentialsSpy).toHaveBeenCalledWith(
      { clientId: "my-client-id", clientSecret: "my-client-secret" },
      { profile: undefined },
    );

    // Verify server was stopped
    expect(stopFn).toHaveBeenCalled();
  });

  it("attempts refresh when refresh token exists in profile", async () => {
    // Pre-create a profile with a refresh token
    loadConfigFileSpy.mockResolvedValue({
      raw: {
        oauth: {
          "access-token": "old-token",
          "client-id": "stored-client-id",
          "client-secret": "stored-client-secret",
          "refresh-token": "existing-refresh-token",
          "token-expires-at": "2025-01-01T00:00:00.000Z",
        },
        "api-version": "202501",
      },
      path: "/some/path.yaml",
    });

    vi.spyOn(core, "refreshAccessToken").mockResolvedValue({
      accessToken: "refreshed-access-token",
      expiresIn: 5184000,
      refreshToken: "new-refresh-token",
      scope: "openid profile",
    });

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    // Should have saved refreshed tokens
    expect(saveOAuthTokensSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        accessToken: "refreshed-access-token",
        refreshToken: "new-refresh-token",
      }),
      { profile: undefined },
    );
  });

  it("falls back to full flow when refresh fails", async () => {
    loadConfigFileSpy.mockResolvedValue({
      raw: {
        oauth: {
          "access-token": "old-token",
          "client-id": "stored-client-id",
          "client-secret": "stored-client-secret",
          "refresh-token": "expired-refresh-token",
          "token-expires-at": "2025-01-01T00:00:00.000Z",
        },
        "api-version": "202501",
      },
      path: "/some/path.yaml",
    });

    vi.spyOn(core, "refreshAccessToken").mockRejectedValue(new Error("refresh failed"));
    mockFullOAuthFlow({ exchangeResult: { accessToken: "fresh-access-token" } });

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    expect(saveOAuthTokensSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        accessToken: "fresh-access-token",
      }),
      { profile: undefined },
    );
  });

  it("uses --client-id and --client-secret flags over profile values", async () => {
    loadConfigFileSpy.mockResolvedValue({
      raw: {
        oauth: {
          "access-token": "old-token",
          "client-id": "profile-client-id",
          "client-secret": "profile-client-secret",
        },
        "api-version": "202501",
      },
      path: "/some/path.yaml",
    });

    const { exchangeSpy } = mockFullOAuthFlow();

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "override-id", "--client-secret", "override-secret"], {
      from: "user",
    });

    // Check that the override values were passed to exchangeAuthorizationCode
    const callConfig = exchangeSpy.mock.calls[0]?.[0];
    expect(callConfig?.clientId).toBe("override-id");
    expect(callConfig?.clientSecret).toBe("override-secret");

    // Check saved values
    expect(saveOAuthClientCredentialsSpy).toHaveBeenCalledWith(
      { clientId: "override-id", clientSecret: "override-secret" },
      { profile: undefined },
    );
  });

  it("generates PKCE code challenge and verifier during full OAuth flow", async () => {
    const { exchangeSpy } = mockFullOAuthFlow();

    const buildAuthSpy = vi.spyOn(core, "buildAuthorizationUrl");

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "my-client-id", "--client-secret", "my-client-secret"], {
      from: "user",
    });

    // Verify buildAuthorizationUrl was called with a code challenge (3rd argument)
    expect(buildAuthSpy).toHaveBeenCalledOnce();
    const codeChallenge = buildAuthSpy.mock.calls[0]?.[2];
    expect(codeChallenge).toBeDefined();
    expect(typeof codeChallenge).toBe("string");

    // Verify exchangeAuthorizationCode was called with a code verifier (3rd argument)
    expect(exchangeSpy).toHaveBeenCalledOnce();
    const codeVerifier = exchangeSpy.mock.calls[0]?.[2];
    expect(codeVerifier).toBeDefined();
    expect(typeof codeVerifier).toBe("string");
  });

  it("proceeds directly to full auth when no refresh token available", async () => {
    // Profile without refresh token (common for Community Management API)
    loadConfigFileSpy.mockResolvedValue({
      raw: {
        oauth: {
          "access-token": "old-token",
          "client-id": "my-id",
          "client-secret": "my-secret",
        },
        "api-version": "202501",
      },
      path: "/some/path.yaml",
    });

    mockFullOAuthFlow({ exchangeResult: { accessToken: "new-token" } });
    const refreshSpy = vi.spyOn(core, "refreshAccessToken");

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    // Should NOT have attempted refresh
    expect(refreshSpy).not.toHaveBeenCalled();

    expect(saveOAuthTokensSpy).toHaveBeenCalledWith(
      expect.objectContaining({
        accessToken: "new-token",
      }),
      { profile: undefined },
    );
  });
});
