// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

import { join } from "node:path";
import { tmpdir } from "node:os";
import { randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { readConfigFile } from "@linkedctl/core";
import * as configFile from "@linkedctl/core";
import * as oauth2 from "@linkedctl/core";
import * as callbackServerModule from "./callback-server.js";
import { loginCommand } from "./login.js";
import { Command } from "commander";
import type { CallbackResult } from "./callback-server.js";

vi.mock("@linkedctl/core", async (importOriginal) => {
  const actual = await importOriginal<typeof configFile>();
  return { ...actual };
});

vi.mock("./callback-server.js", async (importOriginal) => {
  const actual = await importOriginal<typeof callbackServerModule>();
  return { ...actual };
});

vi.mock("node:child_process", () => ({
  execFile: vi.fn(),
}));

function tempConfigPath(): string {
  return join(tmpdir(), `linkedctl-test-${randomUUID()}`, "config.yaml");
}

/** Create a parent program with the --profile option, as login traverses parent. */
function wrapInProgram(cmd: Command): Command {
  const auth = new Command("auth");
  auth.addCommand(cmd);
  const program = new Command("linkedctl");
  program.option("--profile <name>", "profile to use from config file");
  program.addCommand(auth);
  return program;
}

/**
 * Set up mocks for the full OAuth2 flow. Uses a deferred callback pattern
 * so the callback resolves with the correct state generated by randomUUID.
 */
function mockFullOAuthFlow(overrides?: { exchangeResult?: Partial<oauth2.OAuth2TokenResponse> }) {
  const stopFn = vi.fn<() => Promise<void>>().mockResolvedValue(undefined);

  let resolveCallback!: (value: CallbackResult) => void;
  const callbackResult = new Promise<CallbackResult>((resolve) => {
    resolveCallback = resolve;
  });

  vi.spyOn(callbackServerModule, "startCallbackServer").mockResolvedValue({
    port: 12345,
    result: callbackResult,
    stop: stopFn,
  });

  // When buildAuthorizationUrl is called, resolve the callback with the correct state
  vi.spyOn(oauth2, "buildAuthorizationUrl").mockImplementation((_config, state) => {
    resolveCallback({ code: "auth-code-123", state });
    return "https://fake-auth-url";
  });

  const exchangeSpy = vi.spyOn(oauth2, "exchangeAuthorizationCode").mockResolvedValue({
    accessToken: "new-access-token",
    expiresIn: 5184000,
    refreshToken: "new-refresh-token",
    scope: "openid profile w_member_social",
    ...overrides?.exchangeResult,
  });

  return { stopFn, exchangeSpy };
}

describe("auth login", () => {
  let configPath: string;

  beforeEach(() => {
    configPath = tempConfigPath();
    vi.spyOn(configFile, "getDefaultConfigPath").mockReturnValue(configPath);
    vi.spyOn(console, "log").mockImplementation(() => {});
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    await rm(join(configPath, ".."), { recursive: true, force: true });
  });

  it("throws when no client credentials provided", async () => {
    const program = wrapInProgram(loginCommand());

    await expect(program.parseAsync(["auth", "login"], { from: "user" })).rejects.toThrow(/Missing OAuth2 credentials/);
  });

  it("performs full OAuth flow with client credentials from flags", async () => {
    const { stopFn } = mockFullOAuthFlow();

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "my-client-id", "--client-secret", "my-client-secret"], {
      from: "user",
    });

    // Verify tokens were stored
    const config = await readConfigFile(configPath);
    const profile = config.profiles?.["default"];
    expect(profile?.["access-token"]).toBe("new-access-token");
    expect(profile?.["client-id"]).toBe("my-client-id");
    expect(profile?.["client-secret"]).toBe("my-client-secret");
    expect(profile?.["refresh-token"]).toBe("new-refresh-token");
    expect(profile?.["token-expiry"]).toBeDefined();
    expect(config["default-profile"]).toBe("default");

    // Verify server was stopped
    expect(stopFn).toHaveBeenCalled();
  });

  it("attempts refresh when refresh token exists in profile", async () => {
    // Pre-create a profile with a refresh token
    await configFile.writeConfigFile(
      configPath,
      configFile.setDefaultProfile(
        configFile.setProfile({}, "work", {
          "access-token": "old-token",
          "api-version": "202501",
          "client-id": "stored-client-id",
          "client-secret": "stored-client-secret",
          "refresh-token": "existing-refresh-token",
          "token-expiry": "2025-01-01T00:00:00.000Z",
        }),
        "work",
      ),
    );

    vi.spyOn(oauth2, "refreshAccessToken").mockResolvedValue({
      accessToken: "refreshed-access-token",
      expiresIn: 5184000,
      refreshToken: "new-refresh-token",
      scope: "openid profile",
    });

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    // Should have used stored credentials and refreshed
    const config = await readConfigFile(configPath);
    const profile = config.profiles?.["work"];
    expect(profile?.["access-token"]).toBe("refreshed-access-token");
    expect(profile?.["refresh-token"]).toBe("new-refresh-token");
  });

  it("falls back to full flow when refresh fails", async () => {
    await configFile.writeConfigFile(
      configPath,
      configFile.setDefaultProfile(
        configFile.setProfile({}, "work", {
          "access-token": "old-token",
          "api-version": "202501",
          "client-id": "stored-client-id",
          "client-secret": "stored-client-secret",
          "refresh-token": "expired-refresh-token",
          "token-expiry": "2025-01-01T00:00:00.000Z",
        }),
        "work",
      ),
    );

    vi.spyOn(oauth2, "refreshAccessToken").mockRejectedValue(new Error("refresh failed"));
    mockFullOAuthFlow({ exchangeResult: { accessToken: "fresh-access-token" } });

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    const config = await readConfigFile(configPath);
    const profile = config.profiles?.["work"];
    expect(profile?.["access-token"]).toBe("fresh-access-token");
  });

  it("uses --client-id and --client-secret flags over profile values", async () => {
    await configFile.writeConfigFile(
      configPath,
      configFile.setDefaultProfile(
        configFile.setProfile({}, "default", {
          "access-token": "old-token",
          "api-version": "202501",
          "client-id": "profile-client-id",
          "client-secret": "profile-client-secret",
        }),
        "default",
      ),
    );

    const { exchangeSpy } = mockFullOAuthFlow();

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "override-id", "--client-secret", "override-secret"], {
      from: "user",
    });

    // Check that the override values were passed to exchangeAuthorizationCode
    const callConfig = exchangeSpy.mock.calls[0]?.[0];
    expect(callConfig?.clientId).toBe("override-id");
    expect(callConfig?.clientSecret).toBe("override-secret");

    // Check stored values
    const config = await readConfigFile(configPath);
    expect(config.profiles?.["default"]?.["client-id"]).toBe("override-id");
    expect(config.profiles?.["default"]?.["client-secret"]).toBe("override-secret");
  });

  it("generates PKCE code challenge and verifier during full OAuth flow", async () => {
    const { exchangeSpy } = mockFullOAuthFlow();

    const buildAuthSpy = vi.spyOn(oauth2, "buildAuthorizationUrl");

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login", "--client-id", "my-client-id", "--client-secret", "my-client-secret"], {
      from: "user",
    });

    // Verify buildAuthorizationUrl was called with a code challenge (3rd argument)
    expect(buildAuthSpy).toHaveBeenCalledOnce();
    const codeChallenge = buildAuthSpy.mock.calls[0]?.[2];
    expect(codeChallenge).toBeDefined();
    expect(typeof codeChallenge).toBe("string");

    // Verify exchangeAuthorizationCode was called with a code verifier (3rd argument)
    expect(exchangeSpy).toHaveBeenCalledOnce();
    const codeVerifier = exchangeSpy.mock.calls[0]?.[2];
    expect(codeVerifier).toBeDefined();
    expect(typeof codeVerifier).toBe("string");
  });

  it("proceeds directly to full auth when no refresh token available", async () => {
    // Profile without refresh token (common for Community Management API)
    await configFile.writeConfigFile(
      configPath,
      configFile.setDefaultProfile(
        configFile.setProfile({}, "default", {
          "access-token": "old-token",
          "api-version": "202501",
          "client-id": "my-id",
          "client-secret": "my-secret",
        }),
        "default",
      ),
    );

    mockFullOAuthFlow({ exchangeResult: { accessToken: "new-token" } });
    const refreshSpy = vi.spyOn(oauth2, "refreshAccessToken");

    const program = wrapInProgram(loginCommand());
    await program.parseAsync(["auth", "login"], { from: "user" });

    // Should NOT have attempted refresh
    expect(refreshSpy).not.toHaveBeenCalled();

    const config = await readConfigFile(configPath);
    expect(config.profiles?.["default"]?.["access-token"]).toBe("new-token");
  });
});
